[[redirects]]
    from = "https://elastic-dijkstra-8e1243.netlify.app/"
    to = "https://kupeck.net/"
    status = 301
    force = true
[[redirects]]
    from = "/index.html"
    to = "/"
    status = 302
    force = true
    query = {path = ":path"}
[[redirects]]
    from = "/alerts/index.html"
    to = "/alerts"
    status = 302
    force = true
    query = {path = ":path"}
[[redirects]]
    from = "/bats/index.html"
    to = "/bats"
    status = 302
    force = true
    query = {path = ":path"}
[[redirects]]
    from = "/contact/index.html"
    to = "/contact"
    status = 302
    force = true
    query = {path = ":path"}
[[redirects]]
    from = "/contact/success/index.html"
    to = "/contact/success"
    status = 302
    force = true
    query = {path = ":path"}
[[redirects]]
    from = "/converter/index.html"
    to = "/converter"
    status = 302
    force = true
    query = {path = ":path"}
[[redirects]]
    from = "/rythmapp/index.html"
    to = "/rythmapp"
    status = 302
    force = true
    query = {path = ":path"}
[[redirects]]
    from = "/yenkij-web/index.html"
    to = "/yenkij-web"
    status = 302
    force = true
    query = {path = ":path"}